### ISSUE TITLE
About eventemitter MaxListeners warning 

### ISSUE THREAD

**Issue by zxdong262** [tylerlong/manate#2]
In a project with complicated structure, could get warning like: 
```
events.js:46 MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 event listeners added. Use emitter.setMaxListeners() to increase limit
```
for `store`, could use `store.__emitter__.setMaxListeners(0)`, children still could still create many EventEmitter instance, any suggestions?

**Comment by tylerlong** [comment]
In the readme file, I wrote down:

> every emitter.on() must have a corresponding emitter.off(). Otherwise there will be memory leak.

So I tried my best to avoid this issue in the library.

Need a sample project to reproduce this issue. Otherwise I don't know why is there memory leak.

**Comment by tylerlong** [comment]
I reproduced the issue today:

```
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 event listeners added. Use emitter.setMaxListeners() to increase limit
```
>  This warning message is emitted by Node.js when you add more than 10 listeners to a single EventEmitter instance.

I encountered this issue when I tried to convert a complicated proxy to JSON and convert JSON back to proxy.

Not sure what is the root cause but the issue disappeared after I correctly use https://github.com/typestack/class-transformer.

Especially https://github.com/typestack/class-transformer#providing-more-than-one-type-option
We need to let class-transformer know the correct sub type when doing deserialization from JSON.

**Comment by tylerlong** [comment]
Today I encountered this issue again. It is cause by https://react.dev/reference/react/StrictMode

React Strict mode always renders twice. but the dispose code only runs once. So it will cause memory leak.

Let me think how can I resolve it.

**Comment by tylerlong** [comment]
Fixed it. Just make sure everything outside of `useEffect` is "pure".

**Comment by tylerlong** [comment]
If you are using `__emitter__.on`, make sure you use `__emitter__.off` unregister the listeners. It's out of control of this lib.

By the way, `__emitter__` has been renamed to `$e`.
